// Speedcrypt software - The Open-Source for encrypt and decrypt files
// Copyright (C) 2024-2026 Mariano Ortu <https://www.speedcrypt.info/>
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation.

// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.

// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
//https://www.gnu.org/licenses/gpl-3.0.html

using System;
using System.IO;
using System.Security.Cryptography;

using Org.BouncyCastle.Crypto;
using Org.BouncyCastle.Crypto.Modes;
using Org.BouncyCastle.Crypto.Engines;
using Org.BouncyCastle.Crypto.Paddings;
using Org.BouncyCastle.Crypto.Parameters;

namespace Speedcrypt.Crypto.AES
{
    /// <summary>
    /// Created by Mariano Ortu
    /// 
    /// AESencryptor: Provides authenticated AES encryption and decryption for files
    /// using CBC mode with PKCS7 padding and HMAC-SHA256 integrity protection.
    /// </summary>
    ///
    /// <remarks>
    /// This class implements secure file encryption and decryption within the
    /// Speedcrypt framework:
    /// - Encrypts files using AES-CBC with PKCS7 padding
    /// - Supports 128, 192, and 256-bit AES keys
    /// - Generates a cryptographically secure random IV for every encryption
    /// - Stores the IV at the beginning of the encrypted file
    /// - Protects encrypted data with an HMAC-SHA256 authentication tag
    /// - Verifies integrity before attempting decryption
    /// - Uses fixed-time comparison to mitigate timing attacks during HMAC validation
    /// - Processes files using buffered I/O for efficient handling of large files
    /// - Automatically appends the .SPCR extension to encrypted files
    /// - Invokes Passwerr.HandleDecryptionFailure() on authentication or decryption failures
    ///
    /// Security notes:
    /// - A unique IV is generated for every encryption operation
    /// - Independent cryptographic instances prevent state reuse
    /// - Authentication is verified before any plaintext is produced
    /// - Designed to resist tampering and ciphertext modification attacks
    ///
    /// Responsibility for this C# implementation, cryptographic integration,
    /// testing, and validation lies entirely with the author.
    /// </remarks>
    public class AESencryptor
    {
        // High-level production parameter defining the immutable signature extension assigned to active cipher outputs
        public string EncryptedFileExtension { get; private set; } = ".SPCR"; // Speed Crypt default extension

        // Core architectural matrix constraints managing discrete memory allocations and physical boundaries
        private const int BufferSize = 1024 * 1024; // 1 MB operational block size optimized for non-blocking I/O
        private const int IvSize = 16;              // Required AES structural block constraint length
        private const int HmacSize = 32;            // Fixed digest byte size generated by the authentication layer

        /// <summary>
        /// Invokes the native cryptographic provider kernel to populate a cryptographically strong, non-deterministic Initialization Vector.
        /// </summary>
        /// <returns>A unique byte array allocated specifically for block chaining obfuscation.</returns>
        private static byte[] GenerateIV()
        {
            byte[] iv = new byte[IvSize];

            using (var rng = RandomNumberGenerator.Create())
            {
                // Forces low-level physical entropy hardware collections to saturate the target reference memory bounds
                rng.GetBytes(iv);
            }

            return iv;
        }

        /// <summary>
        /// Compares two structural byte arrays utilizing constant-time bitwise operations to systematically eliminate side-channel timing disclosures.
        /// </summary>
        private static bool FixedTimeEquals(byte[] a, byte[] b)
        {
            if (a == null || b == null)
                return false;

            if (a.Length != b.Length)
                return false;

            int diff = 0;

            // Linearly traverses the absolute sequence lengths executing bitwise OR-XOR evaluation loops 
            // to guarantee identical processing latencies regardless of match outcomes
            for (int i = 0; i < a.Length; i++)
            {
                diff |= a[i] ^ b[i];
            }

            return diff == 0;
        }

        /// <summary>
        /// Executes the standard cryptographic serialization workflow, binding raw file structures into authenticated encrypted envelopes.
        /// </summary>
        public void EncryptFile(string inputFilePath, string outputFilePath, byte[] key, int keySize)
        {
            if (key == null)
                throw new ArgumentNullException(nameof(key));

            if (key.Length != keySize / 8)
                throw new ArgumentException("Key length does not match key size.");

            // Assembles target structural output location paths by binding the specialized enterprise crypt signature extension
            string encryptedFile = outputFilePath + EncryptedFileExtension;

            byte[] iv = GenerateIV();

            // Initializes BouncyCastle pipeline engines leveraging CBC block architectures paired with structural PKCS7 text padding wrappers
            BufferedBlockCipher cipher = new PaddedBufferedBlockCipher(new CbcBlockCipher(new AesEngine()));

            // Armors block operational models by cloning input key arrays directly inside unmanaged context instances
            cipher.Init(true, new ParametersWithIV(new KeyParameter((byte[])key.Clone()), iv));

            // Allocates highly optimized low-level sequential I/O data channels to process mass physical files without straining thread loops
            using (FileStream input = new FileStream(inputFilePath, FileMode.Open, FileAccess.Read, FileShare.Read, BufferSize, FileOptions.SequentialScan))

            using (FileStream output = new FileStream(encryptedFile, FileMode.Create, FileAccess.Write, FileShare.None, BufferSize))

            using (HMACSHA256 hmac = new HMACSHA256((byte[])key.Clone()))
            {
                // Commits raw Initialization Vector markers at the absolute beginning of the storage file canvas
                output.Write(iv, 0, iv.Length);

                // Saturates the running authentication pipeline context with the unique session vector data bytes
                hmac.TransformBlock(iv, 0, iv.Length, null, 0);

                byte[] inputBuffer = new byte[BufferSize];

                byte[] outputBuffer = new byte[cipher.GetOutputSize(BufferSize)];

                int read;

                // Iterative block digestion pipeline reading raw data vectors and streaming cipher block bytes dynamically
                while ((read = input.Read(inputBuffer, 0, inputBuffer.Length)) > 0)
                {
                    int produced = cipher.ProcessBytes(inputBuffer, 0, read, outputBuffer, 0);

                    if (produced > 0)
                    {
                        // Commits encrypted block updates immediately onto the non-volatile device storage layout
                        output.Write(outputBuffer, 0, produced);

                        // Forwards finalized ciphertext structural blocks into the rolling integrity digest processor
                        hmac.TransformBlock(outputBuffer, 0, produced, null, 0);
                    }
                }

                // Executes structural trailing block pad configurations flushing outstanding padded bytes to the device
                int finalProduced = cipher.DoFinal(outputBuffer, 0);

                if (finalProduced > 0)
                {
                    output.Write(outputBuffer, 0, finalProduced);

                    hmac.TransformBlock(outputBuffer, 0, finalProduced, null, 0);
                }

                // Solidifies rolling internal cryptographic message streams to finalize the underlying validation sign
                hmac.TransformFinalBlock(Array.Empty<byte>(), 0, 0);

                // Injects the final 32-byte HMAC authentication signature at the absolute terminus of the physical file architecture
                output.Write(hmac.Hash, 0, HmacSize);
            }
        }

        /// <summary>
        /// Processes encrypted structural parameters executing preliminary signature authentication verifications before deciphering payload bytes.
        /// </summary>
        public bool DecryptFile(string inputFilePath, string outputFilePath, byte[] key, int keySize)
        {
            if (key == null)
                throw new ArgumentNullException(nameof(key));

            if (key.Length != keySize / 8)
                throw new ArgumentException("Key length does not match key size.");

            try
            {
                using (FileStream input = new FileStream(inputFilePath, FileMode.Open, FileAccess.Read, FileShare.Read, BufferSize, FileOptions.SequentialScan))
                {
                    // Boundary check verifying that the input contains at least the base protocol overhead layout metrics
                    if (input.Length <= (IvSize + HmacSize))
                        throw new Exception();

                    // Computes ciphertext segment offsets excluding the trailing validation signature
                    long encryptedLength = input.Length - HmacSize;

                    byte[] storedHmac = new byte[HmacSize];

                    // Directs file streams heads to the target signature block index layer
                    input.Position = encryptedLength;

                    input.Read(storedHmac, 0, storedHmac.Length);

                    // Rewinds file pointers back to a zero base status to initiate signature evaluation scans
                    input.Position = 0;

                    using (HMACSHA256 hmac = new HMACSHA256((byte[])key.Clone()))
                    {
                        byte[] buffer = new byte[BufferSize];

                        long remaining = encryptedLength;

                        // Processes payload streams sequentially updating internal signature validation registries
                        while (remaining > 0)
                        {
                            int toRead = (int)Math.Min(buffer.Length, remaining);

                            int read = input.Read(buffer, 0, toRead);

                            if (read <= 0)
                                break;

                            hmac.TransformBlock(buffer, 0, read, null, 0);

                            remaining -= read;
                        }

                        hmac.TransformFinalBlock(Array.Empty<byte>(), 0, 0);

                        // Defensive Boundary Check: Terminates operations loops instantly if signature verification fails
                        if (!FixedTimeEquals(storedHmac, hmac.Hash))
                        {
                            throw new Exception();
                        }
                    }

                    // Integrity Validated: Rewinds stream access parameters to safely start plaintext extraction workflows
                    input.Position = 0;

                    byte[] iv = new byte[IvSize];

                    // Reads the standalone initialization vector context parameters
                    input.Position = 0; // Ensures strict cursor alignment to parse the correct base sector offset
                    input.Read(iv, 0, iv.Length);

                    // Instantiates BouncyCastle decryption modules matching the strict parameters configured at encryption time
                    BufferedBlockCipher cipher = new PaddedBufferedBlockCipher(new CbcBlockCipher(new AesEngine()));

                    cipher.Init(false, new ParametersWithIV(new KeyParameter((byte[])key.Clone()), iv));

                    using (FileStream output = new FileStream(outputFilePath, FileMode.Create, FileAccess.Write, FileShare.None, BufferSize))
                    {
                        long remaining = encryptedLength - IvSize;

                        byte[] inputBuffer = new byte[BufferSize];

                        byte[] outputBuffer = new byte[cipher.GetOutputSize(BufferSize)];

                        // Streams validated ciphertext blocks extracting plaintext segments back to disk
                        while (remaining > 0)
                        {
                            int toRead = (int)Math.Min(inputBuffer.Length, remaining);

                            int read = input.Read(inputBuffer, 0, toRead);

                            if (read <= 0)
                                break;

                            int produced = cipher.ProcessBytes(inputBuffer, 0, read, outputBuffer, 0);

                            if (produced > 0)
                            {
                                output.Write(outputBuffer, 0, produced);
                            }

                            remaining -= read;
                        }

                        // Flushes trailing output pad layers verifying clean PKCS7 schema alignment strings
                        int finalProduced = cipher.DoFinal(outputBuffer, 0);

                        if (finalProduced > 0)
                        {
                            output.Write(outputBuffer, 0, finalProduced);
                        }
                    }
                }

                return true;
            }
            catch
            {
                // Catches pipeline exceptions or authentication failures to invoke global UI alert wrappers safely
                //Passwerr.HandleDecryptionFailure();
                return false;
            }
        }
    }
}