// Speedcrypt software - The Open-Source for encrypt and decrypt files
// Copyright (C) 2024-2026 Mariano Ortu <https://www.speedcrypt.info/>
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation.

// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.

// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
//https://www.gnu.org/licenses/gpl-3.0.html 

using System;
using System.Text;

using Org.BouncyCastle.Security;
using Org.BouncyCastle.Crypto.Generators;

namespace Speedcrypt.Digests.Bcrypt
{
    /// <summary>
    /// Created by Mariano Ortu
    /// 
    /// BCryptBouncy: Provides secure salt generation using BCrypt primitives.
    /// </summary>
    ///
    /// <remarks>
    /// This static class implements BCrypt functionality with the following key features:
    /// - Generates a secure 16-byte salt using BCrypt primitives
    /// - Intended **only** for salt generation, **not** for password derivation
    /// - Ensures salts are cryptographically strong and unique
    /// - Output is a byte array suitable for use in password hashing or key derivation routines
    ///
    /// Technical note:
    /// - Uses SecureRandom from BouncyCastle for cryptographically strong salt generation
    /// - Fully integrated into Speedcrypt framework for secure password handling
    /// - Do **not** use this class to derive password hashes; it is strictly for generating salts
    ///
   /// Responsibility for integration, testing, and any minor adaptation within
    /// lies entirely with the author.
    /// </remarks>
    public static class BCryptBouncy
    {
        /// <summary>
        /// Generates a secure 16-byte salt for BCrypt.
        /// Salt is mandatory for BCrypt to ensure security.
        /// </summary>
        /// <returns>Byte array representing the salt.</returns>
        public static byte[] BcryptSalt()
        {
            byte[] salt = new byte[16];
            new SecureRandom().NextBytes(salt);
            return salt;
        }

        /// <summary>
        /// Computes a BCrypt-derived output for a given input using the specified salt and number of rounds.
        /// The output is Base64-encoded to ensure consistent representation for display and storage.
        ///
        /// <para>
        /// Important: In this framework, BCrypt is used **only** as a cryptographic primitive to process the input with the salt.
        /// It is **not** intended for full password derivation or as a standalone password hashing method.
        /// </para>
        /// </summary>
        /// <param name="password">The input data to process (password or key material).</param>
        /// <param name="salt">The salt to use (must be 16 bytes, securely generated by BCryptBouncy).</param>
        /// <param name="rounds">The number of BCrypt rounds (work factor).</param>
        /// <returns>Base64 string representing the processed output.</returns>
        public static string ComputeBcrypt(string password, byte[] salt, int rounds)
        {
            byte[] passwordBytes = Encoding.UTF8.GetBytes(password);
            byte[] hashBytes = BCrypt.Generate(passwordBytes, salt, rounds);
            return Convert.ToBase64String(hashBytes);
        }
    }
}